### ISSUE TITLE
Small logo enhancement proposal

### ISSUE THREAD

**Issue by amdomanska** [CottageLabs/website#1]
**Background**

Our current logo, featuring the iconic "cottage" shape, has served us well over the years, becoming a recognizable symbol of our brand. However, as we continue to evolve and adapt to modern design trends, I believe there is an opportunity to enhance our logo while retaining its core essence.

**Proposed Changes**

We are suggesting a subtle logo update that will maintain the integrity of the familiar "cottage" shape. The proposed changes include enclosing the shape within a circle, adding "windows" and a "path" to break down the bulky structure.
Advantages

The proposed enhancements offer several advantages for our brand. The resulting logo will have a sleek and modern look, aligning with current design aesthetics. Additionally, the new design will be easier to incorporate into various layouts, allowing for more versatility. Furthermore, the updated logo will have a lighter visual footprint, contributing to a refreshed overall appearance.

**Opportunities**

The redesigned logo also presents exciting opportunities for our brand. The circular shape enables the logo to work effectively in negative color schemes, providing flexibility in different applications. Additionally, the new design opens doors to explore a wider range of color possibilities, allowing us to experiment and create captivating visual experiences.

**Proposed Actions**

To ensure the logo update aligns with our overall brand identity, we will explore potential font adjustments, as suggested by @richard-jones . This will further refine the visual impact of our logo and create a cohesive and harmonious design.

Background

Our current logo, featuring the iconic "cottage" shape, has served us well over the years, becoming a recognizable symbol of our brand. However, as we continue to evolve and adapt to modern design trends, we believe there is an opportunity to enhance our logo while retaining its core essence.
Proposed Changes

We are suggesting a subtle logo update that will maintain the integrity of the familiar "cottage" shape. The proposed changes include enclosing the shape within a circle, adding "windows" and a "path" to break down the bulky structure.
Advantages

The proposed enhancements offer several advantages for our brand. The resulting logo will have a sleek and modern look, aligning with current design aesthetics. Additionally, the new design will be easier to incorporate into various layouts, allowing for more versatility. Furthermore, the updated logo will have a lighter visual footprint, contributing to a refreshed overall appearance.
Opportunities

The redesigned logo also presents exciting opportunities for our brand. The circular shape enables the logo to work effectively in negative color schemes, providing flexibility in different applications. Additionally, the new design opens doors to explore a wider range of color possibilities, allowing us to experiment and create captivating visual experiences.
Proposed Actions

To ensure the logo update aligns with our overall brand identity, we will explore potential font adjustments, as suggested by Richard. This will further refine the visual impact of our logo and create a cohesive and harmonious design.

**Request for Collaboration**

I kindly request your support and collaboration in considering this logo enhancement proposal. I fully understand and value the sentimental attachment to the old logo, my intention is not to critique but to enhance its visual appeal while staying true to its essence.

**Attached**:
1. Two variations of the proposed logo: one in black and white, and another with a black background as the default option for most applications, while the white background version is intended for specific print materials.

2. Exciting and vibrant versions of the proposed logo, designed to showcase the playful and creative potential of the new design. These colourful variations highlight the versatility and dynamic nature of our brand.

![Image](https://github.com/CottageLabs/website/assets/8298769/44598572-95e8-4a35-9b64-d60e7ff8b816)
![Image](https://github.com/CottageLabs/website/assets/8298769/e7d8bb06-c6a4-4fd2-a366-f830a9260bf4)
![Image](https://github.com/CottageLabs/website/assets/8298769/12177f72-1173-492d-82f2-29920a55239e)

![Image](https://github.com/CottageLabs/website/assets/8298769/aab164f1-7d4e-4d6e-be7f-3f9c48414d61)
![Image](https://github.com/CottageLabs/website/assets/8298769/58af3139-6476-4980-b84d-d1ffc6819d8c)
![Image](https://github.com/CottageLabs/website/assets/8298769/631d226a-5ad0-4494-9555-3a5ba0220d5c)
![Image](https://github.com/CottageLabs/website/assets/8298769/8ab51c05-46b0-4982-993e-94c862705bdd)
![Image](https://github.com/CottageLabs/website/assets/8298769/fbde2c2b-91de-479f-aef0-9892ea78ab35)
![Image](https://github.com/CottageLabs/website/assets/8298769/f2bf9a6c-1231-4ee2-90c1-da4e13093568)
![Image](https://github.com/CottageLabs/website/assets/8298769/c2e941be-da4f-46c3-a90b-e8572c9a475b)
![Image](https://github.com/CottageLabs/website/assets/8298769/a6d9af85-2d20-403f-9ce0-ac17bcd0c04a)

**Comment by Steven-Eardley** [comment]
The more I see it the more I like it, I think. 

However, in the interests of making it look less like the cabin of a trawler, would it be possible to try making the window a little bit smaller, and with 4 panes ( a + instead of | ) between the windows?

The 'path' initially looked too busy and eyecatching, but with certain colour schemes it looks great. Can we see without it? Maybe need to embiggen the cottage and lower the ground down so it's not such a big black block.

The rotation... looks junty which I like. Adds interest to the scene.

**Comment by amdomanska** [comment]
@Steven-Eardley I really like the idea of 4 panels! Here you go:
![image](https://github.com/CottageLabs/website/assets/8298769/00672e6e-f037-49a5-b829-b45b67653493)

I advise against removing the path or increasing the size of the cottage in the logo. It is crucial to allow the logo sufficient space to maintain a balanced composition. Enlarging the cottage may create an overwhelming presence, while removing the path risks the background overpowering the logo's visual impact. It is essential to strike a harmonious balance to ensure the logo maintains its intended effect.

![image](https://github.com/CottageLabs/website/assets/8298769/b1833e26-f754-4e3d-8e65-b8ba2c8f13d1)
![image](https://github.com/CottageLabs/website/assets/8298769/33ce66d3-7f40-42ca-a8a8-68aadbb9ce13)

**Comment by amdomanska** [comment]
> Now that I see it, the problem we have with adding more windows is.. Windows.

@Steven-Eardley 

I understand the concern about the resemblance between the windows in our cottage design and the Windows logo due to the four panels. While it is true that windows can share similar characteristics, it's important to consider the specific angles and shapes involved. Are you certain this is the issue?

I slightly adjusted the design, as shown in the attached image. However, it noticeably throws off the balance of the logo. The same imbalance occurs when considering adding another row or column.

Let's keep in mind that maintaining visual harmony is essential, and we should carefully consider any changes we make.

![image](https://github.com/CottageLabs/website/assets/8298769/9e239aef-aca1-498d-b81d-ee9161f44bb7)
![image](https://github.com/CottageLabs/website/assets/8298769/a73a898a-8c5a-4542-a53f-5bd6a85a42fa)

**Comment by Steven-Eardley** [comment]
I do prefer the top one, the offset makes it less Microsoft, and we keep the cottagey look. Maybe it does become a focal point with the crosshairs. Can you do a comparison of a window with zero, one, two dividers?

**Comment by amdomanska** [comment]
@Steven-Eardley 

Here you go!

![image](https://github.com/CottageLabs/website/assets/8298769/9f19b937-142b-4923-8c9f-d6ea3fd231c5)

**Comment by Steven-Eardley** [comment]
I think you were right at the outset (of course!) 2 lines is too busy, none is unsettling. I prefer 2 logically but the middle option is what looks best.

**Comment by richard-jones** [comment]
I think either the second or the third one above is best.  Which works best when shrunk to icon size, like our profile pictures on github do you think?  I'd guess probably the middle one is best, as there's less detail to lose.

**Comment by amdomanska** [comment]
@richard-jones If we don't want to do 4 "equal" parts (as @Steven-Eardley pointed out, it may too much resemble the Windows logo), then I suggest sticking to the second option. The third option seems slightly unbalanced if the window is not divided equally, in my opinion.

**Comment by Steven-Eardley** [comment]
Adding a windowless logo here for my own interest

![cl_windows](https://github.com/CottageLabs/website/assets/1446355/e792b037-b216-4666-b2d0-ee1e7f5add21)
