### ISSUE TITLE
General site feedback RJ 2024-02-27

### ISSUE THREAD

**Issue by richard-jones** [CottageLabs/website#11]
Feedback from using the site during content writing:

1. Can we have the (c) date in the footer always show the current year, so we don't need to update it every year?
2. When you hover the nav (or any black to red link), it moves slightly, can we stop that?
3. The URL for projects should be `/projects/<project name>` to avoid name clashes with the main content
4. Could we remove the pink fade from the top after all, I'm not a big fan of it now I'm using it
5. Colour scheme wise, this seems a lot more pink on my computer than it appeared on the mockups, is there a way to reduce that?

**Comment by amdomanska** [comment]
@richard-jones 

1. done :)
2. done :)
3. done
4. To avoid really flat background I changed that to a very subtle brown. Please have a look and let me know what you think. I'm sure you'll find it much better.
5. I changed the colour from more pinky to more redish ;) I also reduced the amount of it. Please let me know if this looks better, if now I will play with the primmary hover color.
