### ISSUE TITLE
Proposal for New Company Color Palettes

### ISSUE THREAD

**Issue by amdomanska** [CottageLabs/website#3]
### Description

I would like to propose new colour palettes for our company to enhance our visual identity. The aim is to have distinct palettes that align with different aspects of our brand and values. I have created three different palettes with accompanying moodboards to illustrate the desired aesthetic and emotional tone. Please refer to the attached moodboards and color palettes for a visual representation.

1. Dark, Dramatic Palette:
   This palette is intended to convey a sense of high-end technology and cutting-edge solutions while maintaining a professional tone. After the conversation with @richard-jones about focusing our website on technologies and areas of expertise, I believe this palette would align well with this expectations. It should exude a sense of sophistication and highlight our proficiency in the field. The color scheme should be bold, with rich, dark tones and ample contrast, creating a dramatic and impactful visual experience.

![Image](https://github.com/CottageLabs/website/assets/8298769/463d22ba-f34e-460a-9e38-94ad9e7b29c3)

2. People-Focused and Collaborative Palette:
   The second palette aims to emphasize a friendly, young, and modern feel while also providing a sense of comfort and confidence. It should communicate the message of "We know what we're doing, relax, you're in good hands." The colors should be warm, inviting, and promote a collaborative atmosphere.

![Image](https://github.com/CottageLabs/website/assets/8298769/10dbd886-db06-4974-8d02-40019337ef2a)

3. Light and Relaxed Palette:
   The final palette is meant to create a relaxed and peaceful atmosphere. It should embody a friendly and creative approach, while being professional and maintaining a strong relationship with our clients. The colors should be light, calming, and evoke a sense of creativity.

![Image](https://github.com/CottageLabs/website/assets/8298769/69e88d3b-b34b-4cb2-95b4-0bf11aadf066)

In all the proposed palettes, I have strategically incorporated shades of orange and blue to underline our connections to the Open Repository field and emphasize the professional, knowledgeable, and technical aspects of our company. The inclusion of orange shades symbolizes our strong connection to the Open Repository field, signifying our commitment to openness, collaboration, and innovation within this domain. On the other hand, the incorporation of various shades and hues of blue enhances our visual representation of professionalism, expertise, and trustworthiness. Blue, a color widely associated with these qualities, helps to convey our dedication to delivering knowledgeable and technical solutions. By combining these colors harmoniously within each palette, we aim to create a cohesive and visually appealing representation of our brand that resonates with our target audience.

Please review the attached materials and provide your feedback on whether these color palettes align with our company's vision and goals. Your input is greatly appreciated.

**Comment by Steven-Eardley** [comment]
I think the second pallete appeals the most; the first is too 'gamer-y' like a teenager's bedroom. The third to me is nice and relaxing but also a bit wishy-washy. Nursery.

I like the middle's good balance, incorporation of OA orange is great, but I'd sort of miss the (arbitrary) cooler CL colours - the grey and the cold green. Not sure I can think of a good reason for its inclusion from a strategy standpoint, apart from that it's an appealing colour to use for a backdrop where a more dynamic shade will pop.

**Comment by richard-jones** [comment]
I'm largely in agreement with @Steven-Eardley I think.  The first palette does have that "techy" feel, but a lot of technology companies have that kind of thing, and as we are a "Cottage" Lab, I'd probably want to put over less of a "high tech" feel and more of a "we know what we're doing" feel.  For that, the second palette really fits more with what our ethos is about - it's a personal service, a collaboration, etc.

The third option is also nice, like a playground, which would be an interesting contrary position to hold compared to other tech companies, so that would be my second choice, I think. (I love the palette of the data viz in that one, for example, it's got an almost "on paper" feel to it).
