### ISSUE TITLE
Company Website Structure and Functionality

### ISSUE THREAD

**Issue by amdomanska** [CottageLabs/website#4]
**Aim:**
The primary goal of the website is to provide essential information about our company and enable potential clients to explore our project portfolio from various perspectives.

**Assumptions:**
We assume that clients visiting the website may fall into three main categories:

1. Those seeking a general understanding of our services and expertise.
2. Clients with specific needs who want to browse projects based on our areas of expertise (open access infrastructure provider, repository services, data analytics, and visualization).
3. Clients requiring technology-specific expertise, who will explore projects based on technologies used (e.g., programming languages, elasticsearch, etc.).

**Sections**:

1. **Banner**: The top section will feature our logo, a catchy slogan, brief company overview, and logos of current clients.
2. **Our Areas of Expertise**: This section will provide detailed descriptions of each area of expertise along with links to related projects.
3. **How Can We Help**? We will outline the various steps involved in a project's lifecycle, covering design, implementation, testing, deployment, and maintenance. Additionally, we'll present our tech stack categorized into front/backend and dev/ops, with links to browse projects by technology.
4. **Our Projects**: A carousel will display "project tiles" featuring small screenshots/logos and one-sentence descriptions (challenge, solution, success). Each tile will link to a detailed project page. There will also be a link to access the complete project browser.
5.  **Work With Us**: This section will provide insights into our work approach, information about open positions, and our talent pool.

**Project Browser:**
A separate project browser will be accessible from sections 2, 3, 4, and the menu. It will enable users to browse our projects based on expertise and technology stack or view all projects. Each project link will lead to a detailed project page.

** Detailed Project Pages:**
Every project will have its separate page containing screenshots, images, and a comprehensive description of challenges, solutions, and outcomes. Links to the live projects will be provided when applicable.

**Contact Us:**
The "Contact Us" link will remain visible at all times, providing users with relevant email information to reach out to us.

I'm looking forwards to hearing your thoughts on the sections and their order. Do you feel any additional sections are necessary?
Should we include a separate "About Us" section? If so, what information should be included? We aim to avoid explicitly stating that we are a small company, but we can provide details about our partners and a brief description of key team members and their roles.

Note: The wireframes in Figma are intended for basic structuring purposes only and do not represent the final UI design. The focus is on defining the information we want to present and its organization. 

https://www.figma.com/file/b6gSPzMuFXbXsytS4YzA2A/Untitled?type=design&node-id=209%3A480&mode=design&t=AiTez9AQLsWyZMgW-1

**Comment by richard-jones** [comment]
Overall I think this is a good structure, I'm happy with it.

My only slight reservation is around the technologies bit.  It occurs to me that no one comes to us for help with ES, Edges, Ubuntu, Python, Ruby, etc.  If they come to us for specific technologies it's at a much higher level: Data Visualisation, Data Analytics, Data Processing, Samvera/Hyrax, Invenio, DSpace.  We need to make sure not to overcomplicate the technologies bit to stuff that's not relevant, and focus it on the right entities.

**Comment by amdomanska** [comment]
I'm not very attached to the "browse by technology" bit. We definitely can skip it if you think this is not needed. 

@richard-jones What about the "About Us"? In the palette issue, you're mentioning you'd like that personalized "feel", I would therefore strongly suggest introducing the team. Maybe even all of us, with the titles and/or areas of interest?

**Comment by richard-jones** [comment]
I think we should keep the technologies bit, I think we just need to make sure that it's focused on the right things.  Maybe it's more like "technical areas", which allow us to use some key phrases from industry, like "legacy migrations" or "ETL" and such

I do think we should have an About Us page, for sure.  We're still trying to project an image of size greater than we are, which is what puts me off itemising the team.

**Comment by amdomanska** [comment]
> We're still trying to project an image of size greater than we are, which is what puts me off itemising the team.

Yes, but on the other hand, we want to show our personal engagement in projects and collaborative approach, giving the website a personal touch. That's why it would be useful to give the website some faces. Maybe just partners then? We could call you "founders" :)

**Comment by Steven-Eardley** [comment]
Richard is the only founder left :)

We do need to strike a balance between appearing bigger and appearing inpersonal, I'd lean more towards keeping at least some of us on the site so we're recognisable and approachable. I don't have the case studies to back up the theory, however.
